const routes = require('../../src/score/ScoreRoutes.js');
const { test, expect } = require('../TestFramework');

/**
 * NOTE: This class is auto-generated.
 * Do not edit this file manually.
 */
test('submitEmailAddressForEmailIntelligence route', () => {
  expect(routes['submitEmailAddressForEmailIntelligence']).toBeTruthy();
  expect(routes['submitEmailAddressForEmailIntelligence'].method).toBe('POST');
});
