/**
 * NOTE: This class is auto-generated.
 * Do not edit this file manually.
 */
module.exports = {
  "submitEmailAddressForEmailIntelligence": {
    method: "POST",
    path: "/intelligence/email",
    auth: "Basic",
    contentType: "application/x-www-form-urlencoded",
    parameters: {
      "emailAddress": {
        in: "form",
        required: true
      },
      "accountLifecycleEvent": {
        in: "form",
        required: true
      },
      "accountId": {
        in: "form",
        required: false
      },
      "phoneNumber": {
        in: "form",
        required: false
      },
      "deviceId": {
        in: "form",
        required: false
      },
      "externalId": {
        in: "form",
        required: false
      },
      "originatingIp": {
        in: "form",
        required: false
      },
    }
  },
};